### PR TITLE
6 add OIDC auth to mail api

### LINKED ISSUE #6: Add OIDC auth to Mail API
Similar to our other FastAPI services, this is going to require OIDC-based authorization in order to send email through the 
API. And once we have that working, we can also replace the HTTP headers (`X-Mail-From-Address` and `X-Mail-From-Name` at time of writing) with content from the OIDC access token. This will prevent users from sending email on another user's behalf.

### PR DESCRIPTION
**Pull request by jcadam14**
Closes #6 

- Added integration with Oauth2/Keycloak from the regtech-api-commons lib
- Added @required to root GET and /send POST
- Added pytests to test unauthed and authed versions of endpoints, including testing response from /send
- Added pytest env vars to support settings (mail-api and keycloak settings) during testing

With https://github.com/cfpb/regtech-mail-api/issues/8 merged into this branch (on a separate clone I used), coverage got to 85% ;)

### CODE REVIEW

**Review by hkeeler — APPROVED** [review]
Looks good. I think there's just a merge conflict to resolve.

**Review by lchen-2101 — APPROVED** [review]
LGTM

**Comment by lchen-2101** [comment]
oop, conflict again :joy:

**Review by lchen-2101 — APPROVED** [review]
LGTM

**Pull request merged**
